apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dwe-restrict
  namespace: workflow-engine
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: workflow-engine
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: workflow-engine
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
