apiVersion: v1
kind: Secret
metadata:
  name: dwe-secrets
  namespace: workflow-engine
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:postgres@postgres.workflow-engine.svc.cluster.local:5432/workflow"
